-- admin_group
GRANT USAGE, CREATE ON SCHEMA report TO admin_group;
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA report TO admin_group;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA report TO admin_group;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA report TO admin_group;

-- writer_group
GRANT USAGE ON SCHEMA report TO writer_group;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES    IN SCHEMA report TO writer_group;
GRANT USAGE, SELECT                  ON ALL SEQUENCES IN SCHEMA report TO writer_group;
GRANT EXECUTE                        ON ALL FUNCTIONS IN SCHEMA report TO writer_group;

-- readonly_group
GRANT USAGE  ON SCHEMA report TO readonly_group;
GRANT SELECT ON ALL TABLES    IN SCHEMA report TO readonly_group;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA report TO readonly_group;

-- Закрыть PUBLIC
REVOKE ALL ON SCHEMA report      FROM PUBLIC;
REVOKE ALL ON ALL TABLES    IN SCHEMA report FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA report FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA report FROM PUBLIC;


SET ROLE admin_group;

ALTER DEFAULT PRIVILEGES IN SCHEMA report
    GRANT ALL PRIVILEGES ON TABLES    TO admin_group;
ALTER DEFAULT PRIVILEGES IN SCHEMA report
    GRANT ALL PRIVILEGES ON SEQUENCES TO admin_group;
ALTER DEFAULT PRIVILEGES IN SCHEMA report
    GRANT ALL PRIVILEGES ON FUNCTIONS TO admin_group;

ALTER DEFAULT PRIVILEGES IN SCHEMA report
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES    TO writer_group;
ALTER DEFAULT PRIVILEGES IN SCHEMA report
    GRANT USAGE, SELECT                  ON SEQUENCES TO writer_group;
ALTER DEFAULT PRIVILEGES IN SCHEMA report
    GRANT EXECUTE                        ON FUNCTIONS TO writer_group;

ALTER DEFAULT PRIVILEGES IN SCHEMA report
    GRANT SELECT  ON TABLES    TO readonly_group;
ALTER DEFAULT PRIVILEGES IN SCHEMA report
    GRANT EXECUTE ON FUNCTIONS TO readonly_group;

RESET ROLE;